spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/mc-1
    username: root
    password: 090224T@n
  webflux:
    base-path: /address-app/api/v1
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/ #configure it when change eureka sever port
    #  z1: http://localhost:5000/eureka/ # it can have many zone
